language: cpp
os: osx
osx_image: xcode7.3

env:
  # These versions require a version of XCode that is no longer
  # supported by Travis CI.
  - C4DVERSION=12.032 XCODE_VERSION=5.0-10.08-2013.09.18
  - C4DVERSION=13.051 XCODE_VERSION=5.0-10.08-2013.09.18
  - C4DVERSION=14.041 XCODE_VERSION=5.0-10.08-2013.09.18
  # These fixed versions compile with LLVM 6+ (so, including 7.3).
  - C4DVERSION=12.032-llvm6fix
  - C4DVERSION=13.051-llvm6fix
  - C4DVERSION=14.041-llvm6fix
  # These we can compile with XCode 7.3.
  - C4DVERSION=15.064
  - C4DVERSION=16.021
  - C4DVERSION=16.050
  - C4DVERSION=17.048
  - C4DVERSION=18.030

install:
  - mkdir .tmp
  - export PATH=$PATH:$PWD/.tmp

  - .travis/tools/get-ninja v1.7.2 .tmp
  - if [ ! -z "$XCODE_VERSION" ]; then
      .travis/tools/get-xcode-cltools $XCODE_VERSION xcode5;
      export CC=$PWD/xcode5/usr/bin/clang;
      export CXX=$PWD/xcode5/usr/bin/clang++;
    fi

  # Apparently we need this on OSX because otherwise we can run into the error:
  #     /Users/travis/build.sh: line 109: shell_session_update: command not found
  # See travis-ci#6307
  - rvm get stable

  # Install Python3 with Homebrew and then Pip.
  - brew update
  - brew install python3
  - curl -s https://bootstrap.pypa.io/get-pip.py | sudo python3

  # Install the latest version of Craftr 2.x.
  - sudo pip3 install git+https://github.com/craftr-build/craftr.git@development

script:
  - craftr export -d .version=$C4DVERSION
  - craftr build
