language: cpp
os: osx
matrix:
  allow_failures:
    - env: ALLOW_FAILURE=yes
  include:
    - env: C4DVERSION=12.032 ALLOW_FAILURE=yes
      osx_image: xcode6.4
    - env: C4DVERSION=13.051 ALLOW_FAILURE=yes
      osx_image: xcode6.4
    - env: C4DVERSION=14.041 ALLOW_FAILURE=yes
      osx_image: xcode6.4
    - env: C4DVERSION=15.064
      osx_image: xcode7.3
    - env: C4DVERSION=16.021
      osx_image: xcode7.3
    - env: C4DVERSION=16.050
      osx_image: xcode7.3
    - env: C4DVERSION=17.048
      osx_image: xcode7.3
    - env: C4DVERSION=18.030
      osx_image: xcode7.3

install:
  # Install Python3
  - brew update
  - brew install python3
  # Install pip
  - curl -s https://bootstrap.pypa.io/get-pip.py | sudo python3
  # Install the latest development version of Craftr 2.x
  - sudo pip3 install git+https://github.com/craftr-build/craftr.git@development
  # Install the Ninja binary to .tmp/
  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-mac.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp
  - export PATH=$PATH:$PWD/.tmp

script:
  - craftr export -d .version=$C4DVERSION
  - craftr build
